[package]
name = "example_bot"
authors = ["Bytekeeper <bytekeeper@mailbox.org>"]
edition = "2024"
version = "3.6.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsbwapi = { path = ".." }
